import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { saveAs } from 'file-saver';
import { AnalyticsDashboardData, DateRangePreset } from '../types/analytics';

export interface ExportOptions {
  format: 'png' | 'pdf' | 'csv' | 'excel' | 'json';
  quality?: number; // 0-1 for image quality
  includeCharts?: boolean;
  includeData?: boolean;
  filename?: string;
  dateRange?: DateRangePreset;
  title?: string;
  subtitle?: string;
}

export interface ChartExportData {
  element: HTMLElement;
  title: string;
  description?: string;
}

/**
 * Export a single chart as an image
 */
export const exportChartAsImage = async (
  element: HTMLElement,
  options: Partial<ExportOptions> = {}
): Promise<void> => {
  const {
    format = 'png',
    quality = 0.95,
    filename = `chart-${Date.now()}`
  } = options;

  try {
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 2, // Higher resolution
      logging: false,
      useCORS: true,
      allowTaint: true
    });

    if (format === 'png') {
      canvas.toBlob((blob) => {
        if (blob) {
          saveAs(blob, `${filename}.png`);
        }
      }, 'image/png', quality);
    }
  } catch (error) {
    console.error('Failed to export chart as image:', error);
    throw new Error('Chart export failed');
  }
};

/**
 * Export multiple charts as a PDF report
 */
export const exportChartsAsPDF = async (
  charts: ChartExportData[],
  options: Partial<ExportOptions> = {}
): Promise<void> => {
  const {
    filename = `analytics-report-${Date.now()}`,
    title = 'Healthcare Analytics Report',
    subtitle = 'Generated on ' + new Date().toLocaleDateString(),
    dateRange
  } = options;

  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    let currentY = margin;

    // Add header
    pdf.setFontSize(20);
    pdf.setTextColor(0, 0, 0);
    pdf.text(title, margin, currentY);
    currentY += 10;

    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text(subtitle, margin, currentY);
    currentY += 15;

    if (dateRange) {
      pdf.text(
        `Period: ${dateRange.startDate.toLocaleDateString()} - ${dateRange.endDate.toLocaleDateString()}`,
        margin,
        currentY
      );
      currentY += 15;
    }

    // Process each chart
    for (let i = 0; i < charts.length; i++) {
      const chart = charts[i];

      // Check if we need a new page
      if (currentY > pageHeight - 100) {
        pdf.addPage();
        currentY = margin;
      }

      // Add chart title
      pdf.setFontSize(14);
      pdf.setTextColor(0, 0, 0);
      pdf.text(chart.title, margin, currentY);
      currentY += 10;

      if (chart.description) {
        pdf.setFontSize(10);
        pdf.setTextColor(100, 100, 100);
        const splitText = pdf.splitTextToSize(chart.description, contentWidth);
        pdf.text(splitText, margin, currentY);
        currentY += splitText.length * 5;
      }

      // Convert chart to canvas and add to PDF
      const canvas = await html2canvas(chart.element, {
        backgroundColor: '#ffffff',
        scale: 1.5,
        logging: false,
        useCORS: true,
        allowTaint: true
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      // Check if image fits on current page
      if (currentY + imgHeight > pageHeight - margin) {
        pdf.addPage();
        currentY = margin;
      }

      pdf.addImage(imgData, 'PNG', margin, currentY, imgWidth, imgHeight);
      currentY += imgHeight + 15;
    }

    // Add footer
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Page ${i} of ${pageCount} | Generated by Nazmito Analytics`,
        pageWidth - margin,
        pageHeight - 10,
        { align: 'right' }
      );
    }

    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error('Failed to export charts as PDF:', error);
    throw new Error('PDF export failed');
  }
};

/**
 * Export analytics data as CSV
 */
export const exportDataAsCSV = (
  data: AnalyticsDashboardData,
  options: Partial<ExportOptions> = {}
): void => {
  const { filename = `analytics-data-${Date.now()}` } = options;

  try {
    // Prepare CSV data
    const csvRows: string[] = [];

    // Header
    csvRows.push('# Healthcare Analytics Data Export');
    csvRows.push(`# Generated on: ${new Date().toISOString()}`);
    csvRows.push('');

    // Metrics section
    csvRows.push('## Key Metrics');
    csvRows.push('Metric,Value,Unit');

    const metrics = data.metrics;
    csvRows.push(`Total Processed,${metrics.totalProcessed},requests`);
    csvRows.push(`Daily Volume,${metrics.dailyVolume},requests`);
    csvRows.push(`Monthly Volume,${metrics.monthlyVolume},requests`);
    csvRows.push(`Automation Rate,${(metrics.automationRate * 100).toFixed(2)},percent`);
    csvRows.push(`Success Rate,${(metrics.successRate * 100).toFixed(2)},percent`);
    csvRows.push(`Error Rate,${(metrics.errorRate * 100).toFixed(2)},percent`);
    csvRows.push(`Data Quality Score,${(metrics.dataQualityScore * 100).toFixed(2)},percent`);
    csvRows.push(`Cost Savings,${metrics.costSavings},AED`);
    csvRows.push(`ROI Percentage,${metrics.roiPercentage.toFixed(2)},percent`);
    csvRows.push('');

    // Trends section
    csvRows.push('## Processing Trends');
    csvRows.push('Date,Volume,Processing Time (sec),Success Rate,Error Count,Automation Rate');

    data.trends.forEach(trend => {
      csvRows.push([
        trend.date,
        trend.volume.toString(),
        trend.processingTime.toString(),
        trend.successRate.toFixed(4),
        trend.errorCount.toString(),
        trend.automationRate.toFixed(4)
      ].join(','));
    });
    csvRows.push('');

    // Format distribution
    csvRows.push('## Format Distribution');
    csvRows.push('Format,Count,Percentage,Avg Processing Time,Success Rate');

    data.formatDistribution.forEach(format => {
      csvRows.push([
        format.format,
        format.count.toString(),
        format.percentage.toFixed(2),
        format.avgProcessingTime.toString(),
        format.successRate.toFixed(4)
      ].join(','));
    });
    csvRows.push('');

    // Provider performance
    csvRows.push('## Provider Performance');
    csvRows.push('Provider ID,Provider Name,Total Requests,Approval Rate,Avg Response Time,Quality Score');

    data.providerPerformance.forEach(provider => {
      csvRows.push([
        provider.providerId,
        `"${provider.providerName}"`, // Quoted to handle commas in names
        provider.totalRequests.toString(),
        provider.approvalRate.toFixed(4),
        provider.avgResponseTime.toString(),
        provider.qualityScore.toFixed(4)
      ].join(','));
    });

    // Create and download CSV
    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    saveAs(blob, `${filename}.csv`);
  } catch (error) {
    console.error('Failed to export data as CSV:', error);
    throw new Error('CSV export failed');
  }
};

/**
 * Export analytics data as JSON
 */
export const exportDataAsJSON = (
  data: AnalyticsDashboardData,
  options: Partial<ExportOptions> = {}
): void => {
  const { filename = `analytics-data-${Date.now()}` } = options;

  try {
    const exportData = {
      exportInfo: {
        generatedAt: new Date().toISOString(),
        version: '1.0',
        source: 'Nazmito Healthcare Analytics',
        ...options.dateRange && {
          dateRange: {
            start: options.dateRange.startDate.toISOString(),
            end: options.dateRange.endDate.toISOString(),
            label: options.dateRange.label
          }
        }
      },
      data
    };

    const jsonString = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    saveAs(blob, `${filename}.json`);
  } catch (error) {
    console.error('Failed to export data as JSON:', error);
    throw new Error('JSON export failed');
  }
};

/**
 * Main export function that handles all formats
 */
export const exportAnalytics = async (
  data: AnalyticsDashboardData | ChartExportData[],
  options: ExportOptions
): Promise<void> => {
  const { format } = options;

  try {
    switch (format) {
      case 'png':
        if (Array.isArray(data) && data.length > 0) {
          await exportChartAsImage(data[0].element, options);
        } else {
          throw new Error('PNG export requires chart element');
        }
        break;

      case 'pdf':
        if (Array.isArray(data)) {
          await exportChartsAsPDF(data, options);
        } else {
          throw new Error('PDF export requires chart elements');
        }
        break;

      case 'csv':
        if (!Array.isArray(data)) {
          exportDataAsCSV(data, options);
        } else {
          throw new Error('CSV export requires analytics data');
        }
        break;

      case 'json':
        if (!Array.isArray(data)) {
          exportDataAsJSON(data, options);
        } else {
          throw new Error('JSON export requires analytics data');
        }
        break;

      case 'excel':
        // For now, use CSV format for Excel compatibility
        if (!Array.isArray(data)) {
          exportDataAsCSV(data, { ...options, filename: options.filename?.replace('.xlsx', '') });
        } else {
          throw new Error('Excel export requires analytics data');
        }
        break;

      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  } catch (error) {
    console.error('Export failed:', error);
    throw error;
  }
};

/**
 * Utility to capture multiple dashboard sections for PDF export
 */
export const captureDashboardSections = async (
  sectionSelectors: Array<{ selector: string; title: string; description?: string }>
): Promise<ChartExportData[]> => {
  const charts: ChartExportData[] = [];

  for (const section of sectionSelectors) {
    const element = document.querySelector(section.selector) as HTMLElement;
    if (element) {
      charts.push({
        element,
        title: section.title,
        description: section.description
      });
    }
  }

  return charts;
};

/**
 * Format data for easy viewing in exports
 */
export const formatMetricValue = (
  value: number,
  type: 'currency' | 'percentage' | 'number' | 'time'
): string => {
  switch (type) {
    case 'currency':
      return new Intl.NumberFormat('en-AE', {
        style: 'currency',
        currency: 'AED',
        minimumFractionDigits: 0
      }).format(value);

    case 'percentage':
      return `${value.toFixed(2)}%`;

    case 'time':
      const hours = Math.floor(value / 3600);
      const minutes = Math.floor((value % 3600) / 60);
      const seconds = Math.floor(value % 60);

      if (hours > 0) {
        return `${hours}h ${minutes}m ${seconds}s`;
      } else if (minutes > 0) {
        return `${minutes}m ${seconds}s`;
      } else {
        return `${seconds}s`;
      }

    case 'number':
    default:
      return value.toLocaleString();
  }
};
