# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def AssessClinicalRisk(self, demographics: str,recent_observations: str,current_medications: str,observation_count: int,medication_count: int,
        baml_options: BamlCallOptions = {},
    ) -> types.ClinicalRiskAssessment:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="AssessClinicalRisk", args={
            "demographics": demographics,"recent_observations": recent_observations,"current_medications": current_medications,"observation_count": observation_count,"medication_count": medication_count,
        })
        return typing.cast(types.ClinicalRiskAssessment, result.cast_to(types, types, stream_types, False, __runtime__))
    async def CalculateDataQuality(self, demographics_completeness: str,clinical_data_richness: int,medication_data_availability: int,total_data_points: int,
        baml_options: BamlCallOptions = {},
    ) -> types.DataQualityAssessment:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="CalculateDataQuality", args={
            "demographics_completeness": demographics_completeness,"clinical_data_richness": clinical_data_richness,"medication_data_availability": medication_data_availability,"total_data_points": total_data_points,
        })
        return typing.cast(types.DataQualityAssessment, result.cast_to(types, types, stream_types, False, __runtime__))
    async def DetermineSpecialty(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SpecialtyDecision:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="DetermineSpecialty", args={
            "input": input,
        })
        return typing.cast(types.SpecialtyDecision, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessClinicalRisk(self, demographics: str,recent_observations: str,current_medications: str,observation_count: int,medication_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClinicalRiskAssessment, types.ClinicalRiskAssessment]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="AssessClinicalRisk", args={
            "demographics": demographics,"recent_observations": recent_observations,"current_medications": current_medications,"observation_count": observation_count,"medication_count": medication_count,
        })
        return baml_py.BamlStream[stream_types.ClinicalRiskAssessment, types.ClinicalRiskAssessment](
          result,
          lambda x: typing.cast(stream_types.ClinicalRiskAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClinicalRiskAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def CalculateDataQuality(self, demographics_completeness: str,clinical_data_richness: int,medication_data_availability: int,total_data_points: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DataQualityAssessment, types.DataQualityAssessment]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="CalculateDataQuality", args={
            "demographics_completeness": demographics_completeness,"clinical_data_richness": clinical_data_richness,"medication_data_availability": medication_data_availability,"total_data_points": total_data_points,
        })
        return baml_py.BamlStream[stream_types.DataQualityAssessment, types.DataQualityAssessment](
          result,
          lambda x: typing.cast(stream_types.DataQualityAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DataQualityAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DetermineSpecialty(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SpecialtyDecision, types.SpecialtyDecision]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="DetermineSpecialty", args={
            "input": input,
        })
        return baml_py.BamlStream[stream_types.SpecialtyDecision, types.SpecialtyDecision](
          result,
          lambda x: typing.cast(stream_types.SpecialtyDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SpecialtyDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AssessClinicalRisk(self, demographics: str,recent_observations: str,current_medications: str,observation_count: int,medication_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessClinicalRisk", args={
            "demographics": demographics,"recent_observations": recent_observations,"current_medications": current_medications,"observation_count": observation_count,"medication_count": medication_count,
        }, mode="request")
        return result
    async def CalculateDataQuality(self, demographics_completeness: str,clinical_data_richness: int,medication_data_availability: int,total_data_points: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CalculateDataQuality", args={
            "demographics_completeness": demographics_completeness,"clinical_data_richness": clinical_data_richness,"medication_data_availability": medication_data_availability,"total_data_points": total_data_points,
        }, mode="request")
        return result
    async def DetermineSpecialty(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineSpecialty", args={
            "input": input,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AssessClinicalRisk(self, demographics: str,recent_observations: str,current_medications: str,observation_count: int,medication_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessClinicalRisk", args={
            "demographics": demographics,"recent_observations": recent_observations,"current_medications": current_medications,"observation_count": observation_count,"medication_count": medication_count,
        }, mode="stream")
        return result
    async def CalculateDataQuality(self, demographics_completeness: str,clinical_data_richness: int,medication_data_availability: int,total_data_points: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CalculateDataQuality", args={
            "demographics_completeness": demographics_completeness,"clinical_data_richness": clinical_data_richness,"medication_data_availability": medication_data_availability,"total_data_points": total_data_points,
        }, mode="stream")
        return result
    async def DetermineSpecialty(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineSpecialty", args={
            "input": input,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))