# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def GenerateQualityReport(self, validation_result: types.ValidationResult,
        baml_options: BamlCallOptions = {},
    ) -> types.UIFriendlyReport:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateQualityReport", args={
            "validation_result": validation_result,
        })
        return typing.cast(types.UIFriendlyReport, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ValidateHealthcareData(self, data_sample: types.DataSample,
        baml_options: BamlCallOptions = {},
    ) -> types.ValidationResult:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ValidateHealthcareData", args={
            "data_sample": data_sample,
        })
        return typing.cast(types.ValidationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateQualityReport(self, validation_result: types.ValidationResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.UIFriendlyReport, types.UIFriendlyReport]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateQualityReport", args={
            "validation_result": validation_result,
        })
        return baml_py.BamlStream[stream_types.UIFriendlyReport, types.UIFriendlyReport](
          result,
          lambda x: typing.cast(stream_types.UIFriendlyReport, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.UIFriendlyReport, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateHealthcareData(self, data_sample: types.DataSample,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ValidationResult, types.ValidationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ValidateHealthcareData", args={
            "data_sample": data_sample,
        })
        return baml_py.BamlStream[stream_types.ValidationResult, types.ValidationResult](
          result,
          lambda x: typing.cast(stream_types.ValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def GenerateQualityReport(self, validation_result: types.ValidationResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateQualityReport", args={
            "validation_result": validation_result,
        }, mode="request")
        return result
    async def ValidateHealthcareData(self, data_sample: types.DataSample,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ValidateHealthcareData", args={
            "data_sample": data_sample,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def GenerateQualityReport(self, validation_result: types.ValidationResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateQualityReport", args={
            "validation_result": validation_result,
        }, mode="stream")
        return result
    async def ValidateHealthcareData(self, data_sample: types.DataSample,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ValidateHealthcareData", args={
            "data_sample": data_sample,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))