# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions


class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessClinicalLogic(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="AssessClinicalLogic",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.LLMValidationResult, result)

    def ComprehensiveValidation(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.UIFriendlyReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ComprehensiveValidation",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.UIFriendlyReport, result)

    def DetectDataAnomalies(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="DetectDataAnomalies",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.LLMValidationResult, result)

    def GenerateQualityMetrics(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QualityScore:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateQualityMetrics",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.QualityScore, result)

    def GenerateRecommendations(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ActionableItem"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateRecommendations",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(typing.List["types.ActionableItem"], result)

    def ValidateCompliance(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateCompliance",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.LLMValidationResult, result)

    def ValidateMedicalCodes(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateMedicalCodes",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.LLMValidationResult, result)


class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessClinicalLogic(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="AssessClinicalLogic",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.LLMValidationResult, result)

    def ComprehensiveValidation(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.UIFriendlyReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ComprehensiveValidation",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.UIFriendlyReport, result)

    def DetectDataAnomalies(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="DetectDataAnomalies",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.LLMValidationResult, result)

    def GenerateQualityMetrics(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.QualityScore:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateQualityMetrics",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.QualityScore, result)

    def GenerateRecommendations(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.ActionableItem"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateRecommendations",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(typing.List["stream_types.ActionableItem"], result)

    def ValidateCompliance(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateCompliance", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.LLMValidationResult, result)

    def ValidateMedicalCodes(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.LLMValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateMedicalCodes",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.LLMValidationResult, result)
