# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessClinicalRisk(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClinicalRiskAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AssessClinicalRisk", llm_response=llm_response, mode="request")
        return typing.cast(types.ClinicalRiskAssessment, result)

    def CalculateDataQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DataQualityAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CalculateDataQuality", llm_response=llm_response, mode="request")
        return typing.cast(types.DataQualityAssessment, result)

    def DetermineSpecialty(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SpecialtyDecision:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineSpecialty", llm_response=llm_response, mode="request")
        return typing.cast(types.SpecialtyDecision, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AssessClinicalRisk(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClinicalRiskAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AssessClinicalRisk", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClinicalRiskAssessment, result)

    def CalculateDataQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DataQualityAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CalculateDataQuality", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DataQualityAssessment, result)

    def DetermineSpecialty(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SpecialtyDecision:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineSpecialty", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SpecialtyDecision, result)

    