# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineSpecialty(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MedicalSpecialty:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineSpecialty", llm_response=llm_response, mode="request")
        return typing.cast(types.MedicalSpecialty, result)

    def ExtractClinicalAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClinicalAnalysisOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractClinicalAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.ClinicalAnalysisOutput, result)

    def ExtractComplianceAudit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ComplianceAuditOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractComplianceAudit", llm_response=llm_response, mode="request")
        return typing.cast(types.ComplianceAuditOutput, result)

    def ExtractDecisionMaking(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DecisionMakingOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractDecisionMaking", llm_response=llm_response, mode="request")
        return typing.cast(types.DecisionMakingOutput, result)

    def ExtractMedicationAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MedicationAnalysisOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMedicationAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.MedicationAnalysisOutput, result)

    def ExtractRiskAssessment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RiskAssessmentOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractRiskAssessment", llm_response=llm_response, mode="request")
        return typing.cast(types.RiskAssessmentOutput, result)

    def IntegrateFinalDecision(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinalAuthorizationDecision:
        result = self.__options.merge_options(baml_options).parse_response(function_name="IntegrateFinalDecision", llm_response=llm_response, mode="request")
        return typing.cast(types.FinalAuthorizationDecision, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineSpecialty(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MedicalSpecialty:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineSpecialty", llm_response=llm_response, mode="stream")
        return typing.cast(types.MedicalSpecialty, result)

    def ExtractClinicalAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClinicalAnalysisOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractClinicalAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClinicalAnalysisOutput, result)

    def ExtractComplianceAudit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ComplianceAuditOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractComplianceAudit", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ComplianceAuditOutput, result)

    def ExtractDecisionMaking(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DecisionMakingOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractDecisionMaking", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DecisionMakingOutput, result)

    def ExtractMedicationAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MedicationAnalysisOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMedicationAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MedicationAnalysisOutput, result)

    def ExtractRiskAssessment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RiskAssessmentOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractRiskAssessment", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RiskAssessmentOutput, result)

    def IntegrateFinalDecision(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinalAuthorizationDecision:
        result = self.__options.merge_options(baml_options).parse_response(function_name="IntegrateFinalDecision", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinalAuthorizationDecision, result)

    