# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (17)
# #########################################################################

class AuthorizationRationale(BaseModel):
    medical_necessity: typing.Optional[str] = None
    clinical_evidence: typing.List[str]
    cost_justification: typing.Optional[str] = None
    alternative_analysis: typing.Optional[str] = None
    risk_benefit_summary: typing.Optional[str] = None

class ClinicalAnalysisOutput(BaseModel):
    summary: typing.Optional[str] = None
    key_findings: typing.List["ClinicalFinding"]
    disease_progression: typing.Optional[str] = None
    current_health_status: typing.Optional[str] = None
    clinical_necessity_score: typing.Optional[float] = None
    supporting_evidence: typing.List[str]
    concerns: typing.List[str]
    recommendations: typing.List[str]

class ClinicalFinding(BaseModel):
    condition: typing.Optional[str] = None
    severity: typing.Optional[str] = None
    status: typing.Optional[str] = None
    evidence: typing.List[str]
    relevant_history: typing.List[str]

class ComplianceAuditOutput(BaseModel):
    summary: typing.Optional[str] = None
    overall_compliance_status: typing.Optional[types.ComplianceStatus] = None
    uae_regulatory_checks: typing.List["ComplianceCheck"]
    documentation_review: typing.List["DocumentationRequirement"]
    policy_adherence_score: typing.Optional[float] = None
    compliance_gaps: typing.List[str]
    remediation_actions: typing.List[str]
    audit_recommendations: typing.List[str]

class ComplianceCheck(BaseModel):
    regulation: typing.Optional[str] = None
    status: typing.Optional[types.ComplianceStatus] = None
    requirements: typing.List[str]
    gaps_identified: typing.List[str]
    remediation_needed: typing.List[str]

class DecisionMakingOutput(BaseModel):
    summary: typing.Optional[str] = None
    decision_recommendation: typing.Optional[types.DecisionType] = None
    confidence_score: typing.Optional[float] = None
    authorization_rationale: typing.Optional["AuthorizationRationale"] = None
    conditions_for_approval: typing.List[str]
    monitoring_requirements: typing.List[str]
    duration_of_authorization: typing.Optional[int] = None
    cost_analysis: typing.Optional[str] = None
    appeals_considerations: typing.List[str]

class DocumentationRequirement(BaseModel):
    document_type: typing.Optional[str] = None
    required: typing.Optional[bool] = None
    provided: typing.Optional[bool] = None
    quality_assessment: typing.Optional[str] = None
    action_needed: typing.Optional[str] = None

class DrugInteraction(BaseModel):
    drug1: typing.Optional[str] = None
    drug2: typing.Optional[str] = None
    severity: typing.Optional[str] = None
    description: typing.Optional[str] = None
    management_strategy: typing.Optional[str] = None

class FinalAuthorizationDecision(BaseModel):
    decision: typing.Optional[types.DecisionType] = None
    confidence_score: typing.Optional[float] = None
    authorization_number: typing.Optional[str] = None
    valid_duration_days: typing.Optional[int] = None
    conditions: typing.List[str]
    monitoring_plan: typing.List[str]
    cost_summary: typing.Optional[str] = None
    appeal_rights: typing.Optional[str] = None
    effective_date: typing.Optional[str] = None
    review_date: typing.Optional[str] = None

class MedicalHistory(BaseModel):
    labs: typing.Optional[typing.List[str]] = None
    medications: typing.Optional[typing.List[str]] = None
    claims: typing.Optional[typing.List[str]] = None
    conditions: typing.Optional[typing.List[str]] = None

class MedicationAnalysisOutput(BaseModel):
    summary: typing.Optional[str] = None
    current_medications: typing.List[str]
    drug_interactions: typing.List["DrugInteraction"]
    safety_concerns: typing.List["MedicationSafety"]
    medication_necessity_score: typing.Optional[float] = None
    therapeutic_alternatives: typing.List[str]
    cost_effectiveness_notes: typing.List[str]
    monitoring_recommendations: typing.List[str]

class MedicationSafety(BaseModel):
    drug_name: typing.Optional[str] = None
    contraindications: typing.List[str]
    warnings: typing.List[str]
    monitoring_required: typing.List[str]
    dosage_concerns: typing.List[str]

class OutcomePrediction(BaseModel):
    scenario: typing.Optional[str] = None
    probability: typing.Optional[float] = None
    timeframe: typing.Optional[str] = None
    clinical_impact: typing.Optional[str] = None

class PatientContext(BaseModel):
    age: typing.Optional[int] = None
    date_of_birth: typing.Optional[str] = None
    demographics: typing.Optional[typing.Dict[str, str]] = None

class RiskAssessmentOutput(BaseModel):
    summary: typing.Optional[str] = None
    overall_risk_level: typing.Optional[types.RiskLevel] = None
    risk_factors: typing.List["RiskFactor"]
    outcome_predictions: typing.List["OutcomePrediction"]
    cost_benefit_analysis: typing.Optional[str] = None
    recommended_monitoring: typing.List[str]
    risk_mitigation_strategies: typing.List[str]
    follow_up_requirements: typing.List[str]

class RiskFactor(BaseModel):
    factor: typing.Optional[str] = None
    impact_level: typing.Optional[str] = None
    likelihood: typing.Optional[str] = None
    mitigation_strategy: typing.Optional[str] = None

class ServiceRequest(BaseModel):
    description: typing.Optional[str] = None
    code: typing.Optional[str] = None
    activity_code: typing.Optional[str] = None
    diagnosis_code: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
