# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class AgentAnalysis(BaseModel):
    agent_name: typing.Optional[str] = None
    success: typing.Optional[bool] = None
    response: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    error: typing.Optional[str] = None

class ClinicalRiskAssessment(BaseModel):
    overall_risk: typing.Optional[types.RiskLevel] = None
    risk_factors: typing.List[str]
    confidence: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

class DataQualityAssessment(BaseModel):
    overall_score: typing.Optional[float] = None
    completeness_score: typing.Optional[float] = None
    richness_score: typing.Optional[float] = None
    accuracy_score: typing.Optional[float] = None
    recommendations: typing.List[str]
    reasoning: typing.Optional[str] = None

class FinalPreAuthDecision(BaseModel):
    decision: typing.Optional[types.PreAuthDecision] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None
    key_factors: typing.List[str]
    conditions: typing.List[str]
    risk_assessment: typing.Optional[str] = None
    policy_compliance: typing.Optional[str] = None
    recommendation: typing.Optional[str] = None

class SpecialtyDecision(BaseModel):
    specialty: typing.Optional[types.Specialty] = None
    reasoning: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
