# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel


from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (52)
# #########################################################################


class ActionableItem(BaseModel):
    priority: typing.Optional[str] = None
    category: typing.Optional[str] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    fix_suggestion: typing.Optional[str] = None
    estimated_effort: typing.Optional[str] = None
    affected_fields: typing.Optional[typing.List[str]] = None
    regulation_reference: typing.Optional[str] = None


class Address(BaseModel):
    use: typing.Optional[str] = None
    type: typing.Optional[str] = None
    text: typing.Optional[str] = None
    line: typing.Optional[typing.List[str]] = None
    city: typing.Optional[str] = None
    district: typing.Optional[str] = None
    state: typing.Optional[str] = None
    postalCode: typing.Optional[str] = None
    country: typing.Optional[str] = None
    period: typing.Optional["Period"] = None


class Annotation(BaseModel):
    author_reference: typing.Optional["Reference"] = None
    author_string: typing.Optional[str] = None
    time: typing.Optional[str] = None
    text: typing.Optional[str] = None


class Attachment(BaseModel):
    contentType: typing.Optional[str] = None
    language: typing.Optional[str] = None
    data: typing.Optional[str] = None
    url: typing.Optional[str] = None
    size: typing.Optional[int] = None
    hash: typing.Optional[str] = None
    title: typing.Optional[str] = None
    creation: typing.Optional[str] = None


class BundleEntry(BaseModel):
    id: typing.Optional[str] = None
    resource: typing.Optional["FHIRResource"] = None
    fullUrl: typing.Optional[str] = None
    search: typing.Optional["EntrySearch"] = None
    request: typing.Optional["EntryRequest"] = None
    response: typing.Optional["EntryResponse"] = None


class BundleIdentifier(BaseModel):
    use: typing.Optional[str] = None
    type: typing.Optional["CodeableConcept"] = None
    system: typing.Optional[str] = None
    value: typing.Optional[str] = None
    period: typing.Optional["Period"] = None


class BundleMeta(BaseModel):
    lastUpdated: typing.Optional[str] = None
    profile: typing.Optional[typing.List[str]] = None
    source: typing.Optional[str] = None
    tag: typing.Optional[typing.List["Coding"]] = None


class ClaimCareTeam(BaseModel):
    sequence: typing.Optional[int] = None
    provider: typing.Optional["Reference"] = None
    responsible: typing.Optional[bool] = None
    role: typing.Optional["CodeableConcept"] = None
    qualification: typing.Optional["CodeableConcept"] = None


class ClaimDiagnosis(BaseModel):
    sequence: typing.Optional[int] = None
    diagnosis_codeable_concept: typing.Optional["CodeableConcept"] = None
    diagnosis_reference: typing.Optional["Reference"] = None
    type: typing.Optional[typing.List["CodeableConcept"]] = None
    on_admission: typing.Optional["CodeableConcept"] = None
    package_code: typing.Optional["CodeableConcept"] = None


class ClaimInsurance(BaseModel):
    sequence: typing.Optional[int] = None
    focal: typing.Optional[bool] = None
    identifier: typing.Optional["Identifier"] = None
    coverage: typing.Optional["Reference"] = None
    business_arrangement: typing.Optional[str] = None
    pre_auth_ref: typing.Optional[typing.List[str]] = None
    claim_response: typing.Optional["Reference"] = None


class ClaimItem(BaseModel):
    sequence: typing.Optional[int] = None
    care_team_sequence: typing.Optional[typing.List[int]] = None
    diagnosis_sequence: typing.Optional[typing.List[int]] = None
    procedure_sequence: typing.Optional[typing.List[int]] = None
    information_sequence: typing.Optional[typing.List[int]] = None
    revenue: typing.Optional["CodeableConcept"] = None
    category: typing.Optional["CodeableConcept"] = None
    product_or_service: typing.Optional["CodeableConcept"] = None
    modifier: typing.Optional[typing.List["CodeableConcept"]] = None
    program_code: typing.Optional[typing.List["CodeableConcept"]] = None
    serviced_date: typing.Optional[str] = None
    serviced_period: typing.Optional["Period"] = None
    location_codeable_concept: typing.Optional["CodeableConcept"] = None
    location_address: typing.Optional["Address"] = None
    location_reference: typing.Optional["Reference"] = None
    quantity: typing.Optional["Quantity"] = None
    unit_price: typing.Optional["MoneyAmount"] = None
    factor: typing.Optional[float] = None
    net: typing.Optional["MoneyAmount"] = None
    udi: typing.Optional[typing.List["Reference"]] = None
    body_site: typing.Optional[typing.List["CodeableConcept"]] = None
    sub_site: typing.Optional[typing.List["CodeableConcept"]] = None
    encounter: typing.Optional[typing.List["Reference"]] = None
    detail: typing.Optional[typing.List["ClaimItemDetail"]] = None


class ClaimItemDetail(BaseModel):
    sequence: typing.Optional[int] = None
    revenue: typing.Optional["CodeableConcept"] = None
    category: typing.Optional["CodeableConcept"] = None
    product_or_service: typing.Optional["CodeableConcept"] = None
    modifier: typing.Optional[typing.List["CodeableConcept"]] = None
    program_code: typing.Optional[typing.List["CodeableConcept"]] = None
    quantity: typing.Optional["Quantity"] = None
    unit_price: typing.Optional["MoneyAmount"] = None
    factor: typing.Optional[float] = None
    net: typing.Optional["MoneyAmount"] = None
    udi: typing.Optional[typing.List["Reference"]] = None
    sub_detail: typing.Optional[typing.List["ClaimItemSubDetail"]] = None


class ClaimItemSubDetail(BaseModel):
    sequence: typing.Optional[int] = None
    revenue: typing.Optional["CodeableConcept"] = None
    category: typing.Optional["CodeableConcept"] = None
    product_or_service: typing.Optional["CodeableConcept"] = None
    modifier: typing.Optional[typing.List["CodeableConcept"]] = None
    program_code: typing.Optional[typing.List["CodeableConcept"]] = None
    quantity: typing.Optional["Quantity"] = None
    unit_price: typing.Optional["MoneyAmount"] = None
    factor: typing.Optional[float] = None
    net: typing.Optional["MoneyAmount"] = None
    udi: typing.Optional[typing.List["Reference"]] = None


class ClaimPayee(BaseModel):
    type: typing.Optional["CodeableConcept"] = None
    party: typing.Optional["Reference"] = None


class ClaimProcedure(BaseModel):
    sequence: typing.Optional[int] = None
    type: typing.Optional[typing.List["CodeableConcept"]] = None
    date: typing.Optional[str] = None
    procedure_codeable_concept: typing.Optional["CodeableConcept"] = None
    procedure_reference: typing.Optional["Reference"] = None
    udi: typing.Optional[typing.List["Reference"]] = None


class ClaimRelated(BaseModel):
    claim: typing.Optional["Reference"] = None
    relationship: typing.Optional["CodeableConcept"] = None
    reference: typing.Optional["Identifier"] = None


class ClaimResource(BaseModel):
    resourceType: typing.Optional[str] = None
    id: typing.Optional[str] = None
    status: typing.Optional[str] = None
    type: typing.Optional["CodeableConcept"] = None
    use: typing.Optional[str] = None
    patient: typing.Optional["Reference"] = None
    created: typing.Optional[str] = None
    insurer: typing.Optional["Reference"] = None
    provider: typing.Optional["Reference"] = None
    priority: typing.Optional["CodeableConcept"] = None
    fundsReserve: typing.Optional["CodeableConcept"] = None
    authorization_id: typing.Optional[str] = None
    emirate: typing.Optional[str] = None
    related: typing.Optional[typing.List["ClaimRelated"]] = None
    payee: typing.Optional["ClaimPayee"] = None
    referral: typing.Optional["Reference"] = None
    facility: typing.Optional["Reference"] = None
    careTeam: typing.Optional[typing.List["ClaimCareTeam"]] = None
    supportingInfo: typing.Optional[typing.List["ClaimSupportingInfo"]] = None
    diagnosis: typing.Optional[typing.List["ClaimDiagnosis"]] = None
    procedure: typing.Optional[typing.List["ClaimProcedure"]] = None
    insurance: typing.List["ClaimInsurance"]
    item: typing.Optional[typing.List["ClaimItem"]] = None
    total: typing.Optional["MoneyAmount"] = None


class ClaimSupportingInfo(BaseModel):
    sequence: typing.Optional[int] = None
    category: typing.Optional["CodeableConcept"] = None
    code: typing.Optional["CodeableConcept"] = None
    timing_date: typing.Optional[str] = None
    timing_period: typing.Optional["Period"] = None
    value_boolean: typing.Optional[bool] = None
    value_string: typing.Optional[str] = None
    value_quantity: typing.Optional["Quantity"] = None
    value_attachment: typing.Optional["Attachment"] = None
    value_reference: typing.Optional["Reference"] = None
    reason: typing.Optional["Coding"] = None


class CodeableConcept(BaseModel):
    coding: typing.Optional[typing.List["Coding"]] = None
    text: typing.Optional[str] = None


class Coding(BaseModel):
    system: typing.Optional[str] = None
    version: typing.Optional[str] = None
    code: typing.Optional[str] = None
    display: typing.Optional[str] = None
    userSelected: typing.Optional[bool] = None


class DataContext(BaseModel):
    source_system: typing.Optional[str] = None
    emirate: typing.Optional[str] = None
    provider_type: typing.Optional[str] = None
    patient_category: typing.Optional[str] = None
    processing_date: typing.Optional[str] = None
    claim_type: typing.Optional[str] = None


class DataQualityReport(BaseModel):
    bundle_id: typing.Optional[str] = None
    assessed_at: typing.Optional[str] = None
    quality_score: typing.Optional["QualityScore"] = None
    validation_issues: typing.List["ValidationIssue"]
    summary: typing.Optional["DataQualitySummary"] = None
    recommendations: typing.Optional[typing.List[str]] = None
    total_resources: typing.Optional[int] = None
    resources_assessed: typing.Optional[int] = None
    assessment_duration_ms: typing.Optional[int] = None


class DataQualitySummary(BaseModel):
    total_records: typing.Optional[int] = None
    valid_records: typing.Optional[int] = None
    invalid_records: typing.Optional[int] = None
    required_fields_missing: typing.Optional[int] = None
    invalid_formats: typing.Optional[int] = None
    inconsistent_references: typing.Optional[int] = None
    missing_authorization_ids: typing.Optional[int] = None
    invalid_emirates: typing.Optional[int] = None
    unlicensed_providers: typing.Optional[int] = None
    invalid_icd_codes: typing.Optional[int] = None
    invalid_cpt_codes: typing.Optional[int] = None
    deprecated_codes: typing.Optional[int] = None


class DataSample(BaseModel):
    resource_type: typing.Optional[str] = None
    raw_data: typing.Optional[str] = None
    context: typing.Optional["DataContext"] = None


class EntryRequest(BaseModel):
    method: typing.Optional[str] = None
    url: typing.Optional[str] = None
    ifNoneMatch: typing.Optional[str] = None
    ifModifiedSince: typing.Optional[str] = None
    ifMatch: typing.Optional[str] = None
    ifNoneExist: typing.Optional[str] = None


class EntryResponse(BaseModel):
    status: typing.Optional[str] = None
    location: typing.Optional[str] = None
    etag: typing.Optional[str] = None
    lastModified: typing.Optional[str] = None
    outcome: typing.Optional["OperationOutcome"] = None


class EntrySearch(BaseModel):
    mode: typing.Optional[str] = None
    score: typing.Optional[float] = None


class FHIRResource(BaseModel):
    resourceType: typing.Optional[str] = None
    id: typing.Optional[str] = None
    meta: typing.Optional["ResourceMeta"] = None
    implicitRules: typing.Optional[str] = None
    language: typing.Optional[str] = None
    data: typing.Dict[str, str]


class HealthcareBundle(BaseModel):
    resourceType: typing.Optional[str] = None
    id: typing.Optional[str] = None
    meta: typing.Optional["BundleMeta"] = None
    identifier: typing.Optional["BundleIdentifier"] = None
    type: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    total: typing.Optional[int] = None
    authorization_id: typing.Optional[str] = None
    sender: typing.Optional[types.UAEHealthcareEntity] = None
    receiver: typing.Optional[types.UAEHealthcareEntity] = None
    entry: typing.List["BundleEntry"]
    raw_data: typing.Optional[typing.Dict[str, str]] = None
    processing_metadata: typing.Optional["ProcessingMetadata"] = None


class Identifier(BaseModel):
    use: typing.Optional[str] = None
    type: typing.Optional["CodeableConcept"] = None
    system: typing.Optional[str] = None
    value: typing.Optional[str] = None
    period: typing.Optional["Period"] = None
    assigner: typing.Optional["Reference"] = None


class LLMValidationResult(BaseModel):
    validation_passed: typing.Optional[bool] = None
    confidence_score: typing.Optional[float] = None
    issues: typing.List["ValidationIssue"]
    quality_metrics: typing.Dict[str, float]
    processing_time_ms: typing.Optional[int] = None
    model_used: typing.Optional[str] = None


class MedicalCode(BaseModel):
    code: typing.Optional[str] = None
    system: typing.Optional[types.CodingSystem] = None
    display: typing.Optional[str] = None
    version: typing.Optional[str] = None


class MoneyAmount(BaseModel):
    value: typing.Optional[float] = None
    currency: typing.Optional[str] = None


class ObservationComponent(BaseModel):
    code: typing.Optional["CodeableConcept"] = None
    value_quantity: typing.Optional["Quantity"] = None
    value_codeable_concept: typing.Optional["CodeableConcept"] = None
    value_string: typing.Optional[str] = None
    value_boolean: typing.Optional[bool] = None
    value_integer: typing.Optional[int] = None
    value_range: typing.Optional["Range"] = None
    value_ratio: typing.Optional["Ratio"] = None
    value_sampled_data: typing.Optional["SampledData"] = None
    value_time: typing.Optional[str] = None
    value_date_time: typing.Optional[str] = None
    value_period: typing.Optional["Period"] = None
    data_absent_reason: typing.Optional["CodeableConcept"] = None
    interpretation: typing.Optional[typing.List["CodeableConcept"]] = None
    reference_range: typing.Optional[typing.List["ObservationReferenceRange"]] = None


class ObservationReferenceRange(BaseModel):
    low: typing.Optional["Quantity"] = None
    high: typing.Optional["Quantity"] = None
    type: typing.Optional["CodeableConcept"] = None
    applies_to: typing.Optional[typing.List["CodeableConcept"]] = None
    age: typing.Optional["Range"] = None
    text: typing.Optional[str] = None


class ObservationResource(BaseModel):
    resourceType: typing.Optional[str] = None
    id: typing.Optional[str] = None
    status: typing.Optional[str] = None
    category: typing.Optional[typing.List["CodeableConcept"]] = None
    code: typing.Optional["CodeableConcept"] = None
    subject: typing.Optional["Reference"] = None
    encounter: typing.Optional["Reference"] = None
    effective_date_time: typing.Optional[str] = None
    effective_period: typing.Optional["Period"] = None
    issued: typing.Optional[str] = None
    performer: typing.Optional[typing.List["Reference"]] = None
    value_quantity: typing.Optional["Quantity"] = None
    value_codeable_concept: typing.Optional["CodeableConcept"] = None
    value_string: typing.Optional[str] = None
    value_boolean: typing.Optional[bool] = None
    value_integer: typing.Optional[int] = None
    value_range: typing.Optional["Range"] = None
    value_ratio: typing.Optional["Ratio"] = None
    value_sampled_data: typing.Optional["SampledData"] = None
    value_time: typing.Optional[str] = None
    value_date_time: typing.Optional[str] = None
    value_period: typing.Optional["Period"] = None
    data_absent_reason: typing.Optional["CodeableConcept"] = None
    interpretation: typing.Optional[typing.List["CodeableConcept"]] = None
    note: typing.Optional[typing.List["Annotation"]] = None
    body_site: typing.Optional["CodeableConcept"] = None
    method: typing.Optional["CodeableConcept"] = None
    specimen: typing.Optional["Reference"] = None
    device: typing.Optional["Reference"] = None
    reference_range: typing.Optional[typing.List["ObservationReferenceRange"]] = None
    has_member: typing.Optional[typing.List["Reference"]] = None
    derived_from: typing.Optional[typing.List["Reference"]] = None
    component: typing.Optional[typing.List["ObservationComponent"]] = None


class OperationOutcome(BaseModel):
    resourceType: typing.Optional[str] = None
    issue: typing.List["OutcomeIssue"]


class OutcomeIssue(BaseModel):
    severity: typing.Optional[str] = None
    code: typing.Optional[str] = None
    details: typing.Optional["CodeableConcept"] = None
    diagnostics: typing.Optional[str] = None
    location: typing.Optional[typing.List[str]] = None
    expression: typing.Optional[typing.List[str]] = None


class Period(BaseModel):
    start: typing.Optional[str] = None
    end: typing.Optional[str] = None


class ProcessingError(BaseModel):
    code: typing.Optional[str] = None
    message: typing.Optional[str] = None
    field: typing.Optional[str] = None
    value: typing.Optional[str] = None
    severity: typing.Optional[str] = None


class ProcessingMetadata(BaseModel):
    processed_at: typing.Optional[str] = None
    processor_version: typing.Optional[str] = None
    source_format: typing.Optional[str] = None
    source_system: typing.Optional[str] = None
    warnings: typing.Optional[typing.List["ProcessingWarning"]] = None
    errors: typing.Optional[typing.List["ProcessingError"]] = None
    completeness_score: typing.Optional[float] = None
    validity_score: typing.Optional[float] = None
    consistency_score: typing.Optional[float] = None
    total_records: typing.Optional[int] = None
    processed_records: typing.Optional[int] = None
    failed_records: typing.Optional[int] = None


class ProcessingWarning(BaseModel):
    code: typing.Optional[str] = None
    message: typing.Optional[str] = None
    field: typing.Optional[str] = None
    severity: typing.Optional[str] = None


class QualityScore(BaseModel):
    overall_score: typing.Optional[float] = None
    compliance_score: typing.Optional[float] = None
    clinical_logic_score: typing.Optional[float] = None
    data_completeness_score: typing.Optional[float] = None
    code_validity_score: typing.Optional[float] = None
    total_issues: typing.Optional[int] = None
    critical_issues: typing.Optional[int] = None
    error_issues: typing.Optional[int] = None
    warning_issues: typing.Optional[int] = None
    info_issues: typing.Optional[int] = None


class Quantity(BaseModel):
    value: typing.Optional[float] = None
    comparator: typing.Optional[str] = None
    unit: typing.Optional[str] = None
    system: typing.Optional[str] = None
    code: typing.Optional[str] = None


class Range(BaseModel):
    low: typing.Optional["Quantity"] = None
    high: typing.Optional["Quantity"] = None


class Ratio(BaseModel):
    numerator: typing.Optional["Quantity"] = None
    denominator: typing.Optional["Quantity"] = None


class Reference(BaseModel):
    reference: typing.Optional[str] = None
    type: typing.Optional[str] = None
    identifier: typing.Optional["Identifier"] = None
    display: typing.Optional[str] = None


class ResourceMeta(BaseModel):
    versionId: typing.Optional[str] = None
    lastUpdated: typing.Optional[str] = None
    source: typing.Optional[str] = None
    profile: typing.Optional[typing.List[str]] = None
    security: typing.Optional[typing.List["Coding"]] = None
    tag: typing.Optional[typing.List["Coding"]] = None


class SampledData(BaseModel):
    origin: typing.Optional["Quantity"] = None
    period: typing.Optional[float] = None
    factor: typing.Optional[float] = None
    lower_limit: typing.Optional[float] = None
    upper_limit: typing.Optional[float] = None
    dimensions: typing.Optional[int] = None
    data: typing.Optional[str] = None


class ServiceActivity(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[str] = None
    code: typing.Optional["MedicalCode"] = None
    description: typing.Optional[str] = None
    status: typing.Optional[str] = None
    patient_reference: typing.Optional[str] = None
    performer_reference: typing.Optional[str] = None
    encounter_reference: typing.Optional[str] = None
    performed_date: typing.Optional[str] = None
    performed_period: typing.Optional["Period"] = None
    location: typing.Optional[str] = None
    outcome: typing.Optional["CodeableConcept"] = None
    notes: typing.Optional[str] = None
    emirate: typing.Optional[str] = None
    facility_license: typing.Optional[str] = None
    provider_license: typing.Optional[str] = None


class UIFriendlyReport(BaseModel):
    status: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    score: typing.Optional["QualityScore"] = None
    issues_by_severity: typing.Dict[str, typing.List["ValidationIssue"]]
    actionable_items: typing.List["ActionableItem"]
    next_steps: typing.Optional[typing.List[str]] = None


class ValidationIssue(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[types.ValidationType] = None
    severity: typing.Optional[types.ValidationSeverity] = None
    code: typing.Optional[str] = None
    message: typing.Optional[str] = None
    field_path: typing.Optional[str] = None
    expected_value: typing.Optional[str] = None
    actual_value: typing.Optional[str] = None
    resource_type: typing.Optional[str] = None
    resource_id: typing.Optional[str] = None
    suggestions: typing.Optional[typing.List[str]] = None
    regulation_reference: typing.Optional[str] = None
    emirate_specific: typing.Optional[bool] = None


# #########################################################################
# Generated type aliases (0)
# #########################################################################
