# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def DetermineSpecialty(self, patient_context: types.PatientContext,services: typing.List["types.ServiceRequest"],medical_history: types.MedicalHistory,
        baml_options: BamlCallOptions = {},
    ) -> types.MedicalSpecialty:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="DetermineSpecialty", args={
            "patient_context": patient_context,"services": services,"medical_history": medical_history,
        })
        return typing.cast(types.MedicalSpecialty, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractClinicalAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ClinicalAnalysisOutput:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractClinicalAnalysis", args={
            "agent_response": agent_response,
        })
        return typing.cast(types.ClinicalAnalysisOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractComplianceAudit(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ComplianceAuditOutput:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractComplianceAudit", args={
            "agent_response": agent_response,
        })
        return typing.cast(types.ComplianceAuditOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractDecisionMaking(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DecisionMakingOutput:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractDecisionMaking", args={
            "agent_response": agent_response,
        })
        return typing.cast(types.DecisionMakingOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractMedicationAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MedicationAnalysisOutput:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractMedicationAnalysis", args={
            "agent_response": agent_response,
        })
        return typing.cast(types.MedicationAnalysisOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractRiskAssessment(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RiskAssessmentOutput:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractRiskAssessment", args={
            "agent_response": agent_response,
        })
        return typing.cast(types.RiskAssessmentOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def IntegrateFinalDecision(self, clinical_analysis: types.ClinicalAnalysisOutput,medication_analysis: types.MedicationAnalysisOutput,risk_assessment: types.RiskAssessmentOutput,decision_making: types.DecisionMakingOutput,compliance_audit: types.ComplianceAuditOutput,
        baml_options: BamlCallOptions = {},
    ) -> types.FinalAuthorizationDecision:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="IntegrateFinalDecision", args={
            "clinical_analysis": clinical_analysis,"medication_analysis": medication_analysis,"risk_assessment": risk_assessment,"decision_making": decision_making,"compliance_audit": compliance_audit,
        })
        return typing.cast(types.FinalAuthorizationDecision, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineSpecialty(self, patient_context: types.PatientContext,services: typing.List["types.ServiceRequest"],medical_history: types.MedicalHistory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[types.MedicalSpecialty, types.MedicalSpecialty]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DetermineSpecialty", args={
            "patient_context": patient_context,"services": services,"medical_history": medical_history,
        })
        return baml_py.BamlSyncStream[types.MedicalSpecialty, types.MedicalSpecialty](
          result,
          lambda x: typing.cast(types.MedicalSpecialty, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MedicalSpecialty, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractClinicalAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClinicalAnalysisOutput, types.ClinicalAnalysisOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractClinicalAnalysis", args={
            "agent_response": agent_response,
        })
        return baml_py.BamlSyncStream[stream_types.ClinicalAnalysisOutput, types.ClinicalAnalysisOutput](
          result,
          lambda x: typing.cast(stream_types.ClinicalAnalysisOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClinicalAnalysisOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractComplianceAudit(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ComplianceAuditOutput, types.ComplianceAuditOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractComplianceAudit", args={
            "agent_response": agent_response,
        })
        return baml_py.BamlSyncStream[stream_types.ComplianceAuditOutput, types.ComplianceAuditOutput](
          result,
          lambda x: typing.cast(stream_types.ComplianceAuditOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ComplianceAuditOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractDecisionMaking(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DecisionMakingOutput, types.DecisionMakingOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractDecisionMaking", args={
            "agent_response": agent_response,
        })
        return baml_py.BamlSyncStream[stream_types.DecisionMakingOutput, types.DecisionMakingOutput](
          result,
          lambda x: typing.cast(stream_types.DecisionMakingOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DecisionMakingOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractMedicationAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MedicationAnalysisOutput, types.MedicationAnalysisOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractMedicationAnalysis", args={
            "agent_response": agent_response,
        })
        return baml_py.BamlSyncStream[stream_types.MedicationAnalysisOutput, types.MedicationAnalysisOutput](
          result,
          lambda x: typing.cast(stream_types.MedicationAnalysisOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MedicationAnalysisOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractRiskAssessment(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RiskAssessmentOutput, types.RiskAssessmentOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractRiskAssessment", args={
            "agent_response": agent_response,
        })
        return baml_py.BamlSyncStream[stream_types.RiskAssessmentOutput, types.RiskAssessmentOutput](
          result,
          lambda x: typing.cast(stream_types.RiskAssessmentOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RiskAssessmentOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def IntegrateFinalDecision(self, clinical_analysis: types.ClinicalAnalysisOutput,medication_analysis: types.MedicationAnalysisOutput,risk_assessment: types.RiskAssessmentOutput,decision_making: types.DecisionMakingOutput,compliance_audit: types.ComplianceAuditOutput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FinalAuthorizationDecision, types.FinalAuthorizationDecision]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="IntegrateFinalDecision", args={
            "clinical_analysis": clinical_analysis,"medication_analysis": medication_analysis,"risk_assessment": risk_assessment,"decision_making": decision_making,"compliance_audit": compliance_audit,
        })
        return baml_py.BamlSyncStream[stream_types.FinalAuthorizationDecision, types.FinalAuthorizationDecision](
          result,
          lambda x: typing.cast(stream_types.FinalAuthorizationDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FinalAuthorizationDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineSpecialty(self, patient_context: types.PatientContext,services: typing.List["types.ServiceRequest"],medical_history: types.MedicalHistory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetermineSpecialty", args={
            "patient_context": patient_context,"services": services,"medical_history": medical_history,
        }, mode="request")
        return result
    def ExtractClinicalAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractClinicalAnalysis", args={
            "agent_response": agent_response,
        }, mode="request")
        return result
    def ExtractComplianceAudit(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractComplianceAudit", args={
            "agent_response": agent_response,
        }, mode="request")
        return result
    def ExtractDecisionMaking(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractDecisionMaking", args={
            "agent_response": agent_response,
        }, mode="request")
        return result
    def ExtractMedicationAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMedicationAnalysis", args={
            "agent_response": agent_response,
        }, mode="request")
        return result
    def ExtractRiskAssessment(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractRiskAssessment", args={
            "agent_response": agent_response,
        }, mode="request")
        return result
    def IntegrateFinalDecision(self, clinical_analysis: types.ClinicalAnalysisOutput,medication_analysis: types.MedicationAnalysisOutput,risk_assessment: types.RiskAssessmentOutput,decision_making: types.DecisionMakingOutput,compliance_audit: types.ComplianceAuditOutput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IntegrateFinalDecision", args={
            "clinical_analysis": clinical_analysis,"medication_analysis": medication_analysis,"risk_assessment": risk_assessment,"decision_making": decision_making,"compliance_audit": compliance_audit,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineSpecialty(self, patient_context: types.PatientContext,services: typing.List["types.ServiceRequest"],medical_history: types.MedicalHistory,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetermineSpecialty", args={
            "patient_context": patient_context,"services": services,"medical_history": medical_history,
        }, mode="stream")
        return result
    def ExtractClinicalAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractClinicalAnalysis", args={
            "agent_response": agent_response,
        }, mode="stream")
        return result
    def ExtractComplianceAudit(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractComplianceAudit", args={
            "agent_response": agent_response,
        }, mode="stream")
        return result
    def ExtractDecisionMaking(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractDecisionMaking", args={
            "agent_response": agent_response,
        }, mode="stream")
        return result
    def ExtractMedicationAnalysis(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMedicationAnalysis", args={
            "agent_response": agent_response,
        }, mode="stream")
        return result
    def ExtractRiskAssessment(self, agent_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractRiskAssessment", args={
            "agent_response": agent_response,
        }, mode="stream")
        return result
    def IntegrateFinalDecision(self, clinical_analysis: types.ClinicalAnalysisOutput,medication_analysis: types.MedicationAnalysisOutput,risk_assessment: types.RiskAssessmentOutput,decision_making: types.DecisionMakingOutput,compliance_audit: types.ComplianceAuditOutput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="IntegrateFinalDecision", args={
            "clinical_analysis": clinical_analysis,"medication_analysis": medication_analysis,"risk_assessment": risk_assessment,"decision_making": decision_making,"compliance_audit": compliance_audit,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))