# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentAnalysis": types.AgentAnalysis,
    "stream_types.AgentAnalysis": stream_types.AgentAnalysis,

    "types.ClinicalRiskAssessment": types.ClinicalRiskAssessment,
    "stream_types.ClinicalRiskAssessment": stream_types.ClinicalRiskAssessment,

    "types.DataQualityAssessment": types.DataQualityAssessment,
    "stream_types.DataQualityAssessment": stream_types.DataQualityAssessment,

    "types.FinalPreAuthDecision": types.FinalPreAuthDecision,
    "stream_types.FinalPreAuthDecision": stream_types.FinalPreAuthDecision,

    "types.SpecialtyDecision": types.SpecialtyDecision,
    "stream_types.SpecialtyDecision": stream_types.SpecialtyDecision,


    "types.PreAuthDecision": types.PreAuthDecision,

    "types.RiskLevel": types.RiskLevel,

    "types.Specialty": types.Specialty,

}