# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class PreAuthDecision(str, Enum):
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class Specialty(str, Enum):
    Pediatric = "Pediatric"
    Diabetes = "Diabetes"
    Cardiac = "Cardiac"
    Respiratory = "Respiratory"
    Oncology = "Oncology"
    Orthopedic = "Orthopedic"
    Nephrology = "Nephrology"
    Dermatology = "Dermatology"
    Neurology = "Neurology"
    MentalHealth = "MentalHealth"
    General = "General"

# #########################################################################
# Generated classes (5)
# #########################################################################

class AgentAnalysis(BaseModel):
    agent_name: str
    success: bool
    response: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    error: typing.Optional[str] = None

class ClinicalRiskAssessment(BaseModel):
    overall_risk: RiskLevel
    risk_factors: typing.List[str]
    confidence: float
    reasoning: str

class DataQualityAssessment(BaseModel):
    overall_score: float
    completeness_score: float
    richness_score: float
    accuracy_score: float
    recommendations: typing.List[str]
    reasoning: str

class FinalPreAuthDecision(BaseModel):
    decision: PreAuthDecision
    confidence: float
    rationale: str
    key_factors: typing.List[str]
    conditions: typing.List[str]
    risk_assessment: str
    policy_compliance: str
    recommendation: str

class SpecialtyDecision(BaseModel):
    specialty: Specialty
    reasoning: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
