# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ActionableItem": types.ActionableItem,
    "stream_types.ActionableItem": stream_types.ActionableItem,

    "types.DataContext": types.DataContext,
    "stream_types.DataContext": stream_types.DataContext,

    "types.DataSample": types.DataSample,
    "stream_types.DataSample": stream_types.DataSample,

    "types.QualityScore": types.QualityScore,
    "stream_types.QualityScore": stream_types.QualityScore,

    "types.UIFriendlyReport": types.UIFriendlyReport,
    "stream_types.UIFriendlyReport": stream_types.UIFriendlyReport,

    "types.ValidationIssue": types.ValidationIssue,
    "stream_types.ValidationIssue": stream_types.ValidationIssue,

    "types.ValidationResult": types.ValidationResult,
    "stream_types.ValidationResult": stream_types.ValidationResult,


    "types.ValidationSeverity": types.ValidationSeverity,

    "types.ValidationType": types.ValidationType,

}